my_string = input("Введите ваше имя: ")
print(f'Количество букв: {len(my_string)}')
print(f'Ваше имя в ВЕРХНЕМ регистре: {my_string.upper()}')
print(f'Ваше имя в ВЕРХНЕМ регистре: {my_string.lower()}')
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
